# Generated by Django 2.2.1 on 2019-06-25 18:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Table',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('userID', models.TextField()),
                ('productNO', models.TextField()),
                ('lowPRICE', models.TextField()),
            ],
        ),
    ]
